language:  python

python:
  - "2.7"

env:
  - PLONE_VERSION=plone-4.3

matrix:
  include:
    - python: 2.7
      env: PLONE_VERSION=5.0

script: 
  -  bash build_test.sh $PLONE_VERSION

notifications:
  irc:
    channels:
      - "irc.freenode.org#sprint"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
