
service_name: travis-pro
repo_token: 9Gz8lbFOfnCehczzQnPMy49awudPW4Rzz

sudo: required
language: python

services:
 - docker

python:
- '2.7'

matrix:
  include:

  - python: "2.7"
    env: PLONE_VERSION=4.3 PORT=22081

  - python: "2.7"
    env: PLONE_VERSION=4.3 PORT=22082


cache:
  directories:
    - eggs

before_install:
- sudo apt-get -y update 
- sudo apt-get -y upgrade lxc-docker
- docker version
- docker pull zopyx/existdb-22
- docker pull zopyx/existdb-30
- docker run -d -p 127.0.0.1:22081:8080 --name existdb22 zopyx/existdb-22
- docker run -d -p 127.0.0.1:22082:8080 --name existdb30 zopyx/existdb-30

after_success:
 - test -v QA && pip install python-coveralls==2.4.0 || true
 - test -v QA && coveralls || true

script:
- bash build_test.sh $PLONE_VERSION $PORT


notifications:
  irc:
    channels:
    - irc.freenode.org#xml-director
    template:
    - '%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}'

