
service_name: travis-pro
repo_token: 9Gz8lbFOfnCehczzQnPMy49awudPW4Rzz

sudo: required
language: python

services:
 - docker

python:
- '2.7'
env:
  matrix:
  - PLONE_VERSION=plone-4.3
  global:
    secure: W2O1Nhru3ZqgoUZuKf1NxnOfsmM4GzD+xSadM4HhetN1V3oNWrJ4gYnIaJ7wK3qWv8zcwKcWj0KtXETnSOIfyEEn3RS+5Y3l1Ltl3AnRz2vdwKWjeJut+xHcyEfLpUaouIp2JTu96xnMcO8qvWGKnX5jHDTXaIHNq5BKUZtQi/U=


cache:
  directories:
    - eggs

before_install:
- docker pull zopyx/existdb-22
- docker pull zopyx/existdb-30
- docker run -d -p 22081:8080 --name existdb22 zopyx/existdb-22
- docker run -d -p 22082:8080 --name existdb30 zopyx/existdb-30

after_success:
 - test -v QA && pip install python-coveralls==2.4.0 || true
 - test -v QA && coveralls || true

matrix:
  include:
  - python: 2.7
    env: PLONE_VERSION=plone-5.0
script:
- bash build_test.sh $PLONE_VERSION


notifications:
  irc:
    channels:
    - irc.freenode.org#xml-director
    template:
    - '%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}'

