service_name: travis-pro
repo_token: 9Gz8lbFOfnCehczzQnPMy49awudPW4Rzz

sudo: required
dist: trusty
language: python

services:
 - docker

matrix:
  include:

  - python: "2.7"
    env: TYPE=LOCAL_FS PLONE_VERSION=4.3 CONNECTOR_URL=file:///tmp/testing

  - python: "2.7"
    env: TYPE=LOCAL_FS PLONE_VERSION=5.1 CONNECTOR_URL=file:///tmp/testing

  - python: "2.7"
    env: TYPE=EXIST22 PLONE_VERSION=4.3 CONNECTOR_URL=http://localhost:8080/exist/webdav/db DOCKER=zopyx/existdb-22

  - python: "2.7"
    env: TYPE=EXIST22 PLONE_VERSION=5.1 CONNECTOR_URL=http://localhost:8080/exist/webdav/db DOCKER=zopyx/existdb-22

  - python: "2.7"
    env: TYPE=EXIST30 PLONE_VERSION=4.3 CONNECTOR_URL=http://localhost:8080/exist/webdav/db DOCKER=zopyx/existdb-30

  - python: "2.7"
    env: TYPE=EXIST30 PLONE_VERSION=5.1 CONNECTOR_URL=http://localhost:8080/exist/webdav/db DOCKER=zopyx/existdb-30

  - python: "2.7"
    env: TYPE=BASEX83 PLONE_VERSION=4.3 CONNECTOR_URL=http://localhost:8080/webdav DOCKER=zopyx/basex-83

  - python: "2.7"
    env: TYPE=BASEX83 PLONE_VERSION=5.1 CONNECTOR_URL=http://localhost:8080/webdav DOCKER=zopyx/basex-83

  - python: "2.7"
    env: TYPE=ALFRESCO PLONE_VERSION=4.3 CONNECTOR_URL=http://localhost:8080/alfresco/webdav DOCKER=gui81/alfresco

  - python: "2.7"
    env: TYPE=ALFRESCO PLONE_VERSION=5.1 CONNECTOR_URL=http://localhost:8080/alfresco/webdav DOCKER=gui81/alfresco

  - python: "2.7"
    env: 
      - TYPE=S3 PLONE_VERSION=4.3 CONNECTOR_URL=s3://ajung-xxxxxxxx
      - secure: "PHMtmJWrAiR+pPMXequDU3ysFc5AME8KlFN/qp7xkfVMhW+z5DAtzEZtziL4J3Ux8teO7Mlv/cVt6DYd9bBMh3590secDrtYpYZbGgpjC1U43P0OXIOgH8QmBDnij2vD42uo3Ycniq8JTq81PTKiZ1eTT7fBTQeUKltMpymmNOI="

      - secure: "FM+R1Z3aqG6OKCePprnJhpa3rP/+2rc0yd602ehTo4YiUlxhpUhCgsVsGZRFCwJhS791rmK3DiaDju5+c18983Kv+1MHEflIzzDI//024H6Sv+ZUkXyDTbWCMrewEZBqVwaa0GBGLjKqXnoKVy+ij6s4hbns6jm5lYgvjVn20d0="

  - python: "2.7"
    env: 
      - TYPE=S3 PLONE_VERSION=5.1 CONNECTOR_URL=s3://ajung-xxxxxxxx
      - secure: "PHMtmJWrAiR+pPMXequDU3ysFc5AME8KlFN/qp7xkfVMhW+z5DAtzEZtziL4J3Ux8teO7Mlv/cVt6DYd9bBMh3590secDrtYpYZbGgpjC1U43P0OXIOgH8QmBDnij2vD42uo3Ycniq8JTq81PTKiZ1eTT7fBTQeUKltMpymmNOI="

      - secure: "FM+R1Z3aqG6OKCePprnJhpa3rP/+2rc0yd602ehTo4YiUlxhpUhCgsVsGZRFCwJhS791rmK3DiaDju5+c18983Kv+1MHEflIzzDI//024H6Sv+ZUkXyDTbWCMrewEZBqVwaa0GBGLjKqXnoKVy+ij6s4hbns6jm5lYgvjVn20d0="

  - python: "2.7"
    env: 
      - TYPE=OWNCLOUD PLONE_VERSION=4.3 
      - secure: "mf6+DuUR37+mWEpIec+y++8Gaj8bcUO5VDKIDT/0u1fu9naGKPSgvWeY/yzO1ZTchv559Xnn4WUVi1OhIrJqCUhzhSRGqzRx6mIqtzpT+keb+HYT7geReZo3EsPOOqTx0edVAB+ej/2t4qtvnsTkkHu8K1YaPXbap0ConBKlBxs="

      - secure: "KEHwBEW3FEvlkLIzZEcGeTn7imDKc3Xgh/wyokUh+H0HDTYpStQX57/HhVN3MlFto3iO4j6ajuWX17nH4K77mBcgHNfZpStQh0UMzMATqVy/6/OnAwpJUotr40g/LK8MXkwWeJv3f3Slfbq6NZWfUizm1eONVd5Q6amNXLK4dzE="
      - secure: "M2xqyRSELsLLZJWbHGVXd+104bWq0BEVkjpUrbZOg+P6fwETpSiQYaUPvktTIeeXVa8mBfmcg/ZcLLavDculvAZLJFxDXzcqayhnFznZou62e9cQo+q1HnVWKYQ+OlDFRxHatXfiPT+491qZ1VKxed2VdtnWiPRxHniYFtX5N3M="

  - python: "2.7"
    env: 
      - TYPE=OWNCLOUD PLONE_VERSION=5.1 
      - secure: "mf6+DuUR37+mWEpIec+y++8Gaj8bcUO5VDKIDT/0u1fu9naGKPSgvWeY/yzO1ZTchv559Xnn4WUVi1OhIrJqCUhzhSRGqzRx6mIqtzpT+keb+HYT7geReZo3EsPOOqTx0edVAB+ej/2t4qtvnsTkkHu8K1YaPXbap0ConBKlBxs="

      - secure: "KEHwBEW3FEvlkLIzZEcGeTn7imDKc3Xgh/wyokUh+H0HDTYpStQX57/HhVN3MlFto3iO4j6ajuWX17nH4K77mBcgHNfZpStQh0UMzMATqVy/6/OnAwpJUotr40g/LK8MXkwWeJv3f3Slfbq6NZWfUizm1eONVd5Q6amNXLK4dzE="
      - secure: "M2xqyRSELsLLZJWbHGVXd+104bWq0BEVkjpUrbZOg+P6fwETpSiQYaUPvktTIeeXVa8mBfmcg/ZcLLavDculvAZLJFxDXzcqayhnFznZou62e9cQo+q1HnVWKYQ+OlDFRxHatXfiPT+491qZ1VKxed2VdtnWiPRxHniYFtX5N3M="


cache:
  directories:
    - eggs

before_install:
- sudo apt-get -y update 
#- sudo apt-get -y upgrade lxc-docker
- docker version
#- docker pull gui81/alfresco
#- docker pull owncloud:8.1

after_success:
 - test -v QA && pip install python-coveralls==2.4.0 || true
 - test -v QA && coveralls || true

script:
- pwd
- ls -la
- mkdir -p /tmp/testing
- rm -fr /tmp/testing/*
- bash build_test.sh 

notifications:
  irc:
    channels:
    - irc.freenode.org#xml-director
    template:
    - '%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}'
