service_name: travis-pro
repo_token: 9Gz8lbFOfnCehczzQnPMy49awudPW4Rzz

sudo: required
language: python

services:
 - docker

matrix:
  include:

  - python: "2.7"
    env: PLONE_VERSION=4.3 WEBDAV_URL=http://localhost:22081/exist/webdav/db

  - python: "2.7"
    env: PLONE_VERSION=4.3 WEBDAV_URL=http://localhost:22082/exist/webdav/db

  - python: "2.7"
    env: PLONE_VERSION=4.3 WEBDAV_URL=http://localhost:22083/webdav

  - python: "2.7"
    env: PLONE_VERSION=5.0 WEBDAV_URL=http://localhost:22081/exist/webdav/db

  - python: "2.7"
    env: PLONE_VERSION=5.0 WEBDAV_URL=http://localhost:22082/exist/webdav/db

  - python: "2.7"
    env: PLONE_VERSION=5.0 WEBDAV_URL=http://localhost:22083/webdav

cache:
  directories:
    - eggs

before_install:
- sudo apt-get -y update 
- sudo apt-get -y upgrade lxc-docker
- docker version
- docker pull zopyx/existdb-22
- docker pull zopyx/existdb-30
- docker pull zopyx/basex-83
- docker run -d -p 127.0.0.1:22081:8080 --name existdb22 zopyx/existdb-22
- docker run -d -p 127.0.0.1:22082:8080 --name existdb30 zopyx/existdb-30
- docker run -d -p 127.0.0.1:22083:8080 --name basex83   zopyx/basex-83

after_success:
 - test -v QA && pip install python-coveralls==2.4.0 || true
 - test -v QA && coveralls || true

script:
- sudo bash build_test.sh 


notifications:
  irc:
    channels:
    - irc.freenode.org#xml-director
    template:
    - '%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}'

